services:
  r_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
  r_test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: test
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # Overrides Default Startup command
    
