# use an existing docker image as base
FROM alpine:latest

# download and install a dependency
RUN apk add --update redis
RUN apk add --update gcc

# tell the image what todo when it starts as a container
CMD ["redis-server"]

