# version: "3" # obselete remove it
services:
  redis-server:
    image: "redis:latest"
    container_name: "redis-server"
    ports:
      - "6379:6379"
  redis-counter:
    build: .
    container_name: "redis-counter-application"
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - "redis-server"